# Generated by Django 2.1.5 on 2020-05-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MlDividends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.TextField(blank=True, null=True)),
                ('company', models.TextField(blank=True, null=True)),
                ('sector', models.TextField(blank=True, null=True)),
                ('pay_type', models.TextField(blank=True, null=True)),
                ('load_date', models.DateField(blank=True, null=True)),
                ('prevclose', models.FloatField(blank=True, null=True)),
                ('targetprice', models.FloatField(blank=True, null=True)),
                ('orders', models.TextField(blank=True, null=True)),
                ('dividend', models.FloatField(blank=True, null=True)),
                ('increased', models.FloatField(blank=True, null=True)),
                ('payment_date', models.TextField(blank=True, null=True)),
                ('payout', models.FloatField(blank=True, null=True)),
                ('dividendyield', models.FloatField(blank=True, null=True)),
                ('p_e', models.FloatField(blank=True, null=True)),
                ('growth_pe', models.BigIntegerField(blank=True, null=True)),
                ('good_div', models.BigIntegerField(blank=True, null=True)),
                ('healthy_div', models.BigIntegerField(blank=True, null=True)),
                ('highrisk_div', models.BigIntegerField(blank=True, null=True)),
                ('bad_div', models.BigIntegerField(blank=True, null=True)),
                ('basic_materials', models.BigIntegerField(blank=True, db_column='Basic Materials', null=True)),
                ('conglomerates', models.BigIntegerField(blank=True, db_column='Conglomerates', null=True)),
                ('consumer_goods', models.BigIntegerField(blank=True, db_column='Consumer Goods', null=True)),
                ('financial', models.BigIntegerField(blank=True, db_column='Financial', null=True)),
                ('healthcare', models.BigIntegerField(blank=True, db_column='Healthcare', null=True)),
                ('industrial_goods', models.BigIntegerField(blank=True, db_column='Industrial Goods', null=True)),
                ('services', models.BigIntegerField(blank=True, db_column='Services', null=True)),
                ('technology', models.BigIntegerField(blank=True, db_column='Technology', null=True)),
                ('utilities', models.BigIntegerField(blank=True, db_column='Utilities', null=True)),
            ],
            options={
                'db_table': 'ML_DIVIDENDS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TechnicalDivs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.TextField(blank=True, null=True)),
                ('number_52wlow', models.TextField(blank=True, db_column='52wlow', null=True)),
                ('number_52whigh', models.TextField(blank=True, db_column='52whigh', null=True)),
                ('perfquarter', models.TextField(blank=True, null=True)),
                ('perfhalfy', models.TextField(blank=True, null=True)),
                ('perfmonth', models.TextField(blank=True, null=True)),
                ('perfweek', models.TextField(blank=True, null=True)),
                ('perfyear', models.TextField(blank=True, null=True)),
                ('perfytd', models.TextField(blank=True, null=True)),
                ('prevclose', models.TextField(blank=True, null=True)),
                ('price', models.TextField(blank=True, null=True)),
                ('targetprice', models.TextField(blank=True, null=True)),
                ('atr', models.TextField(blank=True, null=True)),
                ('rsi', models.TextField(blank=True, null=True)),
                ('volatility', models.TextField(blank=True, null=True)),
                ('optionable', models.TextField(blank=True, null=True)),
                ('relvolume', models.TextField(blank=True, null=True)),
                ('shortable', models.TextField(blank=True, null=True)),
                ('payout', models.TextField(blank=True, null=True)),
                ('avgvolume', models.FloatField(blank=True, null=True)),
                ('recom', models.TextField(blank=True, null=True)),
                ('sma20', models.TextField(blank=True, null=True)),
                ('sma50', models.TextField(blank=True, null=True)),
                ('sma200', models.TextField(blank=True, null=True)),
                ('volume', models.TextField(blank=True, null=True)),
                ('change', models.TextField(blank=True, null=True)),
                ('beta', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'TECHNICAL_DIVS',
                'managed': False,
            },
        ),
    ]
