# Generated by Django 2.1.5 on 2020-06-30 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200630_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='stockup_project/home/static/home/img/profileImg.png', upload_to='users/%Y/%m/%d/'),
        ),
    ]
