# Generated by Django 2.1.5 on 2020-07-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200713_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstockportfolio',
            name='pay_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
