# Generated by Django 2.1.5 on 2020-06-30 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200630_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='profileimg.png', upload_to='users/%Y/%m/%d/'),
        ),
    ]
