# Generated by Django 3.0.8 on 2020-08-04 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userstockprofittracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstockportfolio',
            name='broker',
            field=models.CharField(blank=True, choices=[('Robinhood', 'Robinhood'), ('E-trade', 'E-trade'), ('Fidelity', 'Fidelity'), ('TDAmeritrade', 'TDAmeritrade')], max_length=30, null=True),
        ),
    ]
