# Generated by Django 3.0.8 on 2020-08-13 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userstockportfolio_broker'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldStockPortfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=30, null=True)),
                ('company', models.CharField(blank=True, max_length=150, null=True)),
                ('sector', models.CharField(blank=True, max_length=30, null=True)),
                ('broker', models.CharField(blank=True, max_length=30, null=True)),
                ('pay_type', models.CharField(blank=True, max_length=30, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('dividends', models.FloatField(blank=True, null=True)),
                ('n_shares', models.IntegerField(blank=True, null=True)),
                ('tot_price', models.FloatField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Profile')),
            ],
        ),
    ]
