# Generated by Django 2.1.5 on 2020-06-30 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200630_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='stockup_project/home/static/home/img/profileimg.png', null=True, upload_to='users/%Y/%m/%d/'),
        ),
    ]
