# Generated by Django 3.0.8 on 2020-08-14 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_soldstockportfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldstockportfolio',
            name='stock_id',
            field=models.IntegerField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userstockportfolio',
            name='purchased',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
