# Generated by Django 3.0.8 on 2020-08-14 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200814_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldstockportfolio',
            name='stock_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
