# Generated by Django 3.0.8 on 2020-08-14 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200814_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldstockportfolio',
            name='stock_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
