version: '3.8'

services:
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8888
        volumes:
            - .stockup_project/:/usr/src/stockup_porject
        ports:
            - 8888:8888
        env_file:
            - .env
        depends_on:
            - postgres-db
            - mysql-db
    
    postgres-db:
        image: postgres:latest
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - NAMEDB_POST
            - USER_POST
            - PASSWORD_POST
    
    mysql-db:
        image: mysql:latest
        volumes:
            - mysql_data:/var/lib/mysql/data
        environment:
            - NAMEDB_MYSQL
            - USER_MYSQL    
            - PASSWORD_MYSQL